<?php

return [
    'home' => 'Back to Home',
    'listing' => 'Back to Europe',
    'virtualService' => 'Virtual Service',
    'prefixOf' => 'of',
    'currency' => '€',
    'perHour' => '/hour',
    'age' => 'years old',
    'toMeet' => 'To meet',
    'escortIn' => 'Escort in',
    'iAttendIn' => 'I attend in',
    'escort' => 'Escort',
    'prefixIn' => 'in',
    'onNeighborhood' => 'on the neighborhood',
    'iAttend' => 'I attend',
    'only' => 'only',
    'and' => 'and',
    'currentlyAttending' => 'currently attending',
    'noPlace' => 'No place',
    'ownPlace' => 'Own place',
    'incall' => 'Incall',
    'outcall' => 'Outcall',
    'meet' => 'Meet :name, :location Escort.',
    'servicesOffered' => 'Services offered',
    'checkOut' => 'Check out',
    'photos' => 'photos',
    'videos' => 'videos',
    'europe' => 'Europe',
];
