export default {
  attention: 'Attention',
  blocked: 'blocked',
  cancel: 'Cancel',
  confirm: 'Confirm',
  confirmAndReplace: 'Confirm and replace',
  currencyCode: 'U$',
  exclusive: 'exclusive',
  new: 'novo',
  untold: 'Untold',
  readLess: 'Read less',
  readMore: 'Read more',
  remove: 'Remove',
  seeMore: 'See more',
  seeLess: 'See less',
  seeContent: 'See content',
  share: 'Share',
  yes: 'Yes',
  no: 'No',
  noDataReported: 'No data reported', // não informado
  doesNotPerform: 'Does not perform',
  and: 'and',
  cipher: '€',
  perHour: '/hour',
  perHourShort: '/h',
  agree: 'I agree',
  learnMore: 'Learn more',
  none: 'None'
}
